// AUTO-GENERATED by packages/db/scripts/generate-types.mjs — do not hand-edit.
// Regenerate after any migration change: `pnpm --filter @ngc/db gen:types`
// (requires DATABASE_URL to point at a Postgres instance with all migrations applied).
//
// Once this project is linked to a real hosted Supabase project, prefer
// `supabase gen types typescript --project-id <ref> > src/database.types.ts`
// instead — the shape below matches its output, so nothing else needs to change.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
    _id_sequences: {
      Row: {
      sequence_key: string;
      year: number;
      last_value: number;
      };
      Insert: {
      sequence_key: string;
      year: number;
      last_value?: number;
      };
      Update: {
      sequence_key?: string;
      year?: number;
      last_value?: number;
      };
      Relationships: [];
    };
    agendas: {
      Row: {
      id: string;
      title: string;
      description: string | null;
      voting_method: string;
      eligible_voter_scope: string;
      eligible_department_id: string | null;
      eligible_family_id: string | null;
      eligible_user_ids: string[];
      is_anonymous: boolean;
      voting_deadline: string;
      status: string;
      created_by: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      title: string;
      description?: string | null;
      voting_method?: string;
      eligible_voter_scope?: string;
      eligible_department_id?: string | null;
      eligible_family_id?: string | null;
      eligible_user_ids?: string[];
      is_anonymous?: boolean;
      voting_deadline: string;
      status?: string;
      created_by: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      title?: string;
      description?: string | null;
      voting_method?: string;
      eligible_voter_scope?: string;
      eligible_department_id?: string | null;
      eligible_family_id?: string | null;
      eligible_user_ids?: string[];
      is_anonymous?: boolean;
      voting_deadline?: string;
      status?: string;
      created_by?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    announcements: {
      Row: {
      id: string;
      title: string;
      message: string;
      image_url: string | null;
      attachment_document_id: string | null;
      target_audience: string;
      target_department_id: string | null;
      target_family_id: string | null;
      target_event_id: string | null;
      target_user_ids: string[];
      priority: string;
      publish_at: string;
      expiry_at: string | null;
      author_id: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      title: string;
      message: string;
      image_url?: string | null;
      attachment_document_id?: string | null;
      target_audience?: string;
      target_department_id?: string | null;
      target_family_id?: string | null;
      target_event_id?: string | null;
      target_user_ids?: string[];
      priority?: string;
      publish_at?: string;
      expiry_at?: string | null;
      author_id: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      title?: string;
      message?: string;
      image_url?: string | null;
      attachment_document_id?: string | null;
      target_audience?: string;
      target_department_id?: string | null;
      target_family_id?: string | null;
      target_event_id?: string | null;
      target_user_ids?: string[];
      priority?: string;
      publish_at?: string;
      expiry_at?: string | null;
      author_id?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    application_documents: {
      Row: {
      id: string;
      application_id: string;
      document_type: string;
      file_path: string;
      original_filename: string | null;
      uploaded_at: string;
      };
      Insert: {
      id?: string;
      application_id: string;
      document_type: string;
      file_path: string;
      original_filename?: string | null;
      uploaded_at?: string;
      };
      Update: {
      id?: string;
      application_id?: string;
      document_type?: string;
      file_path?: string;
      original_filename?: string | null;
      uploaded_at?: string;
      };
      Relationships: [];
    };
    applications: {
      Row: {
      id: string;
      application_number: string;
      application_type: string;
      access_token_hash: string;
      verification_contact: string;
      existing_member_id: string | null;
      submitted_data: Json;
      previous_data: Json | null;
      status: string;
      completion_percentage: number;
      missing_fields: string[];
      reviewed_by: string | null;
      reviewed_at: string | null;
      decision_reason: string | null;
      decision_letter_document_id: string | null;
      submitted_at: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      application_number: string;
      application_type?: string;
      access_token_hash: string;
      verification_contact: string;
      existing_member_id?: string | null;
      submitted_data?: Json;
      previous_data?: Json | null;
      status?: string;
      completion_percentage?: number;
      missing_fields?: string[];
      reviewed_by?: string | null;
      reviewed_at?: string | null;
      decision_reason?: string | null;
      decision_letter_document_id?: string | null;
      submitted_at?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      application_number?: string;
      application_type?: string;
      access_token_hash?: string;
      verification_contact?: string;
      existing_member_id?: string | null;
      submitted_data?: Json;
      previous_data?: Json | null;
      status?: string;
      completion_percentage?: number;
      missing_fields?: string[];
      reviewed_by?: string | null;
      reviewed_at?: string | null;
      decision_reason?: string | null;
      decision_letter_document_id?: string | null;
      submitted_at?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    asset_assignments: {
      Row: {
      id: string;
      asset_id: string;
      target_type: string;
      target_id: string;
      quantity: number;
      assigned_by: string | null;
      assigned_at: string;
      expected_return_at: string | null;
      returned_at: string | null;
      return_condition: string | null;
      damage_report: string | null;
      status: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      asset_id: string;
      target_type: string;
      target_id: string;
      quantity?: number;
      assigned_by?: string | null;
      assigned_at?: string;
      expected_return_at?: string | null;
      returned_at?: string | null;
      return_condition?: string | null;
      damage_report?: string | null;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      asset_id?: string;
      target_type?: string;
      target_id?: string;
      quantity?: number;
      assigned_by?: string | null;
      assigned_at?: string;
      expected_return_at?: string | null;
      returned_at?: string | null;
      return_condition?: string | null;
      damage_report?: string | null;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    asset_categories: {
      Row: {
      id: string;
      name: string;
      description: string | null;
      is_active: boolean;
      created_at: string;
      };
      Insert: {
      id?: string;
      name: string;
      description?: string | null;
      is_active?: boolean;
      created_at?: string;
      };
      Update: {
      id?: string;
      name?: string;
      description?: string | null;
      is_active?: boolean;
      created_at?: string;
      };
      Relationships: [];
    };
    assets: {
      Row: {
      id: string;
      asset_tag: string;
      category_id: string;
      name: string;
      serial_number: string | null;
      purchase_date: string | null;
      purchase_value: number | null;
      current_value: number | null;
      currency: string;
      condition: string;
      location: string | null;
      custodian_user_id: string | null;
      owning_department_id: string | null;
      availability_status: string;
      photo_urls: string[];
      qr_token: string;
      disposed_at: string | null;
      disposal_reason: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      asset_tag: string;
      category_id: string;
      name: string;
      serial_number?: string | null;
      purchase_date?: string | null;
      purchase_value?: number | null;
      current_value?: number | null;
      currency?: string;
      condition?: string;
      location?: string | null;
      custodian_user_id?: string | null;
      owning_department_id?: string | null;
      availability_status?: string;
      photo_urls?: string[];
      qr_token?: string;
      disposed_at?: string | null;
      disposal_reason?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      asset_tag?: string;
      category_id?: string;
      name?: string;
      serial_number?: string | null;
      purchase_date?: string | null;
      purchase_value?: number | null;
      current_value?: number | null;
      currency?: string;
      condition?: string;
      location?: string | null;
      custodian_user_id?: string | null;
      owning_department_id?: string | null;
      availability_status?: string;
      photo_urls?: string[];
      qr_token?: string;
      disposed_at?: string | null;
      disposal_reason?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    attendance: {
      Row: {
      id: string;
      session_id: string;
      member_id: string;
      status_code: string;
      recorded_via: string;
      recorded_by: string | null;
      client_idempotency_key: string | null;
      notes: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      session_id: string;
      member_id: string;
      status_code?: string;
      recorded_via?: string;
      recorded_by?: string | null;
      client_idempotency_key?: string | null;
      notes?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      session_id?: string;
      member_id?: string;
      status_code?: string;
      recorded_via?: string;
      recorded_by?: string | null;
      client_idempotency_key?: string | null;
      notes?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    attendance_sessions: {
      Row: {
      id: string;
      session_type: string;
      title: string;
      department_id: string | null;
      event_id: string | null;
      session_date: string;
      starts_at: string | null;
      ends_at: string | null;
      created_by: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      session_type: string;
      title: string;
      department_id?: string | null;
      event_id?: string | null;
      session_date: string;
      starts_at?: string | null;
      ends_at?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      session_type?: string;
      title?: string;
      department_id?: string | null;
      event_id?: string | null;
      session_date?: string;
      starts_at?: string | null;
      ends_at?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    audit_logs: {
      Row: {
      id: string;
      actor_id: string | null;
      action: string;
      module: string | null;
      record_type: string;
      record_id: string | null;
      before_value: Json | null;
      after_value: Json | null;
      ip_address: string | null;
      device_info: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      actor_id?: string | null;
      action: string;
      module?: string | null;
      record_type: string;
      record_id?: string | null;
      before_value?: Json | null;
      after_value?: Json | null;
      ip_address?: string | null;
      device_info?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      actor_id?: string | null;
      action?: string;
      module?: string | null;
      record_type?: string;
      record_id?: string | null;
      before_value?: Json | null;
      after_value?: Json | null;
      ip_address?: string | null;
      device_info?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    comments: {
      Row: {
      id: string;
      owner_type: string;
      owner_id: string;
      author_id: string;
      body: string;
      is_internal: boolean;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      owner_type: string;
      owner_id: string;
      author_id: string;
      body: string;
      is_internal?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      owner_type?: string;
      owner_id?: string;
      author_id?: string;
      body?: string;
      is_internal?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    contribution_campaigns: {
      Row: {
      id: string;
      name: string;
      description: string | null;
      target_amount: number | null;
      currency: string;
      deadline: string | null;
      status: string;
      created_by: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      name: string;
      description?: string | null;
      target_amount?: number | null;
      currency?: string;
      deadline?: string | null;
      status?: string;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      name?: string;
      description?: string | null;
      target_amount?: number | null;
      currency?: string;
      deadline?: string | null;
      status?: string;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    contribution_records: {
      Row: {
      id: string;
      campaign_id: string;
      member_id: string;
      amount: number;
      currency: string;
      contributed_at: string;
      payment_method: string | null;
      reference: string | null;
      status: string;
      notes: string | null;
      recorded_by: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      campaign_id: string;
      member_id: string;
      amount: number;
      currency?: string;
      contributed_at?: string;
      payment_method?: string | null;
      reference?: string | null;
      status?: string;
      notes?: string | null;
      recorded_by?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      campaign_id?: string;
      member_id?: string;
      amount?: number;
      currency?: string;
      contributed_at?: string;
      payment_method?: string | null;
      reference?: string | null;
      status?: string;
      notes?: string | null;
      recorded_by?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    departments: {
      Row: {
      id: string;
      name: string;
      description: string | null;
      leader_user_id: string | null;
      is_active: boolean;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      name: string;
      description?: string | null;
      leader_user_id?: string | null;
      is_active?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      name?: string;
      description?: string | null;
      leader_user_id?: string | null;
      is_active?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    disciplinary_actions: {
      Row: {
      id: string;
      case_id: string;
      action_type: string;
      decided_by: string;
      decided_at: string;
      suspension_start_date: string | null;
      suspension_end_date: string | null;
      resolution: string | null;
      restored_by: string | null;
      restored_at: string | null;
      restoration_reason: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      case_id: string;
      action_type: string;
      decided_by: string;
      decided_at?: string;
      suspension_start_date?: string | null;
      suspension_end_date?: string | null;
      resolution?: string | null;
      restored_by?: string | null;
      restored_at?: string | null;
      restoration_reason?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      case_id?: string;
      action_type?: string;
      decided_by?: string;
      decided_at?: string;
      suspension_start_date?: string | null;
      suspension_end_date?: string | null;
      resolution?: string | null;
      restored_by?: string | null;
      restored_at?: string | null;
      restoration_reason?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    disciplinary_cases: {
      Row: {
      id: string;
      case_number: string;
      member_id: string;
      category: string;
      incident_date: string;
      description: string;
      evidence_document_ids: string[];
      officer_id: string;
      status: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      case_number: string;
      member_id: string;
      category: string;
      incident_date: string;
      description: string;
      evidence_document_ids?: string[];
      officer_id: string;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      case_number?: string;
      member_id?: string;
      category?: string;
      incident_date?: string;
      description?: string;
      evidence_document_ids?: string[];
      officer_id?: string;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    document_categories: {
      Row: {
      id: string;
      name: string;
      is_confidential: boolean;
      created_at: string;
      };
      Insert: {
      id?: string;
      name: string;
      is_confidential?: boolean;
      created_at?: string;
      };
      Update: {
      id?: string;
      name?: string;
      is_confidential?: boolean;
      created_at?: string;
      };
      Relationships: [];
    };
    document_versions: {
      Row: {
      id: string;
      document_id: string;
      version_number: number;
      file_path: string;
      file_size_bytes: number | null;
      uploaded_by: string | null;
      uploaded_at: string;
      };
      Insert: {
      id?: string;
      document_id: string;
      version_number: number;
      file_path: string;
      file_size_bytes?: number | null;
      uploaded_by?: string | null;
      uploaded_at?: string;
      };
      Update: {
      id?: string;
      document_id?: string;
      version_number?: number;
      file_path?: string;
      file_size_bytes?: number | null;
      uploaded_by?: string | null;
      uploaded_at?: string;
      };
      Relationships: [];
    };
    documents: {
      Row: {
      id: string;
      category_id: string;
      owner_type: string | null;
      owner_id: string | null;
      title: string;
      tags: string[];
      owner_user_id: string | null;
      expiry_date: string | null;
      status: string;
      archived_by: string | null;
      archived_at: string | null;
      restore_reason: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      category_id: string;
      owner_type?: string | null;
      owner_id?: string | null;
      title: string;
      tags?: string[];
      owner_user_id?: string | null;
      expiry_date?: string | null;
      status?: string;
      archived_by?: string | null;
      archived_at?: string | null;
      restore_reason?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      category_id?: string;
      owner_type?: string | null;
      owner_id?: string | null;
      title?: string;
      tags?: string[];
      owner_user_id?: string | null;
      expiry_date?: string | null;
      status?: string;
      archived_by?: string | null;
      archived_at?: string | null;
      restore_reason?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    event_attendance: {
      Row: {
      id: string;
      event_id: string;
      member_id: string;
      status_code: string;
      recorded_via: string;
      recorded_by: string | null;
      client_idempotency_key: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      event_id: string;
      member_id: string;
      status_code?: string;
      recorded_via?: string;
      recorded_by?: string | null;
      client_idempotency_key?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      event_id?: string;
      member_id?: string;
      status_code?: string;
      recorded_via?: string;
      recorded_by?: string | null;
      client_idempotency_key?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    event_participants: {
      Row: {
      id: string;
      event_id: string;
      member_id: string;
      assignment_source: string;
      override_reason: string | null;
      overridden_by: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      event_id: string;
      member_id: string;
      assignment_source?: string;
      override_reason?: string | null;
      overridden_by?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      event_id?: string;
      member_id?: string;
      assignment_source?: string;
      override_reason?: string | null;
      overridden_by?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    event_requirements: {
      Row: {
      id: string;
      event_id: string;
      requirement_type: string;
      description: string;
      created_at: string;
      };
      Insert: {
      id?: string;
      event_id: string;
      requirement_type: string;
      description: string;
      created_at?: string;
      };
      Update: {
      id?: string;
      event_id?: string;
      requirement_type?: string;
      description?: string;
      created_at?: string;
      };
      Relationships: [];
    };
    events: {
      Row: {
      id: string;
      invitation_id: string | null;
      name: string;
      event_category: string;
      event_date: string;
      start_time: string | null;
      end_time: string | null;
      venue: string | null;
      location: string | null;
      status: string;
      qr_token: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      invitation_id?: string | null;
      name: string;
      event_category?: string;
      event_date: string;
      start_time?: string | null;
      end_time?: string | null;
      venue?: string | null;
      location?: string | null;
      status?: string;
      qr_token?: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      invitation_id?: string | null;
      name?: string;
      event_category?: string;
      event_date?: string;
      start_time?: string | null;
      end_time?: string | null;
      venue?: string | null;
      location?: string | null;
      status?: string;
      qr_token?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    expense_requests: {
      Row: {
      id: string;
      request_number: string;
      requested_by: string;
      description: string;
      amount: number;
      currency: string;
      category: string | null;
      department_id: string | null;
      event_id: string | null;
      supporting_document_id: string | null;
      status: string;
      paid_at: string | null;
      payment_reference: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      request_number: string;
      requested_by: string;
      description: string;
      amount: number;
      currency?: string;
      category?: string | null;
      department_id?: string | null;
      event_id?: string | null;
      supporting_document_id?: string | null;
      status?: string;
      paid_at?: string | null;
      payment_reference?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      request_number?: string;
      requested_by?: string;
      description?: string;
      amount?: number;
      currency?: string;
      category?: string | null;
      department_id?: string | null;
      event_id?: string | null;
      supporting_document_id?: string | null;
      status?: string;
      paid_at?: string | null;
      payment_reference?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    families: {
      Row: {
      id: string;
      name: string;
      description: string | null;
      leader_user_id: string | null;
      is_active: boolean;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      name: string;
      description?: string | null;
      leader_user_id?: string | null;
      is_active?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      name?: string;
      description?: string | null;
      leader_user_id?: string | null;
      is_active?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    gate_pass_items: {
      Row: {
      id: string;
      gate_pass_id: string;
      asset_id: string;
      quantity: number;
      checked_out_at: string | null;
      returned_at: string | null;
      return_condition: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      gate_pass_id: string;
      asset_id: string;
      quantity?: number;
      checked_out_at?: string | null;
      returned_at?: string | null;
      return_condition?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      gate_pass_id?: string;
      asset_id?: string;
      quantity?: number;
      checked_out_at?: string | null;
      returned_at?: string | null;
      return_condition?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    gate_passes: {
      Row: {
      id: string;
      gate_pass_number: string;
      event_id: string;
      person_responsible_id: string;
      department_id: string | null;
      expected_departure: string | null;
      expected_return: string | null;
      status: string;
      qr_token: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      gate_pass_number: string;
      event_id: string;
      person_responsible_id: string;
      department_id?: string | null;
      expected_departure?: string | null;
      expected_return?: string | null;
      status?: string;
      qr_token?: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      gate_pass_number?: string;
      event_id?: string;
      person_responsible_id?: string;
      department_id?: string | null;
      expected_departure?: string | null;
      expected_return?: string | null;
      status?: string;
      qr_token?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    invitations: {
      Row: {
      id: string;
      invitation_number: string;
      organizer_name: string;
      organizer_contact_email: string | null;
      organizer_contact_phone: string | null;
      organization_name: string | null;
      event_name: string;
      event_type: string | null;
      proposed_date: string;
      proposed_time: string | null;
      venue: string | null;
      location: string | null;
      region: string | null;
      expected_audience: number | null;
      nature_of_invitation: string | null;
      performance_requirements: string | null;
      technical_requirements: string | null;
      transport_requirements: string | null;
      accommodation_requirements: string | null;
      financial_information: string | null;
      additional_notes: string | null;
      access_token_hash: string;
      verification_contact: string;
      status: string;
      submitted_at: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      invitation_number: string;
      organizer_name: string;
      organizer_contact_email?: string | null;
      organizer_contact_phone?: string | null;
      organization_name?: string | null;
      event_name: string;
      event_type?: string | null;
      proposed_date: string;
      proposed_time?: string | null;
      venue?: string | null;
      location?: string | null;
      region?: string | null;
      expected_audience?: number | null;
      nature_of_invitation?: string | null;
      performance_requirements?: string | null;
      technical_requirements?: string | null;
      transport_requirements?: string | null;
      accommodation_requirements?: string | null;
      financial_information?: string | null;
      additional_notes?: string | null;
      access_token_hash: string;
      verification_contact: string;
      status?: string;
      submitted_at?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      invitation_number?: string;
      organizer_name?: string;
      organizer_contact_email?: string | null;
      organizer_contact_phone?: string | null;
      organization_name?: string | null;
      event_name?: string;
      event_type?: string | null;
      proposed_date?: string;
      proposed_time?: string | null;
      venue?: string | null;
      location?: string | null;
      region?: string | null;
      expected_audience?: number | null;
      nature_of_invitation?: string | null;
      performance_requirements?: string | null;
      technical_requirements?: string | null;
      transport_requirements?: string | null;
      accommodation_requirements?: string | null;
      financial_information?: string | null;
      additional_notes?: string | null;
      access_token_hash?: string;
      verification_contact?: string;
      status?: string;
      submitted_at?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    itineraries: {
      Row: {
      id: string;
      trip_id: string;
      assigned_member_ids: string[];
      generated_at: string;
      generated_document_id: string | null;
      notes: string | null;
      };
      Insert: {
      id?: string;
      trip_id: string;
      assigned_member_ids?: string[];
      generated_at?: string;
      generated_document_id?: string | null;
      notes?: string | null;
      };
      Update: {
      id?: string;
      trip_id?: string;
      assigned_member_ids?: string[];
      generated_at?: string;
      generated_document_id?: string | null;
      notes?: string | null;
      };
      Relationships: [];
    };
    leave_requests: {
      Row: {
      id: string;
      member_id: string;
      leave_type: string;
      reason: string;
      start_date: string;
      end_date: string;
      supporting_document_id: string | null;
      status: string;
      approved_by: string | null;
      approved_at: string | null;
      approver_comment: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      member_id: string;
      leave_type: string;
      reason: string;
      start_date: string;
      end_date: string;
      supporting_document_id?: string | null;
      status?: string;
      approved_by?: string | null;
      approved_at?: string | null;
      approver_comment?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      member_id?: string;
      leave_type?: string;
      reason?: string;
      start_date?: string;
      end_date?: string;
      supporting_document_id?: string | null;
      status?: string;
      approved_by?: string | null;
      approved_at?: string | null;
      approver_comment?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    lookup_values: {
      Row: {
      id: string;
      category: string;
      code: string;
      label: string;
      sort_order: number;
      is_active: boolean;
      metadata: Json;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      category: string;
      code: string;
      label: string;
      sort_order?: number;
      is_active?: boolean;
      metadata?: Json;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      category?: string;
      code?: string;
      label?: string;
      sort_order?: number;
      is_active?: boolean;
      metadata?: Json;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    media_links: {
      Row: {
      id: string;
      event_id: string | null;
      link_type: string;
      url: string;
      title: string | null;
      shared_with_roles: string[];
      shared_with_department_ids: string[];
      shared_with_member_ids: string[];
      is_published: boolean;
      created_by: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      event_id?: string | null;
      link_type: string;
      url: string;
      title?: string | null;
      shared_with_roles?: string[];
      shared_with_department_ids?: string[];
      shared_with_member_ids?: string[];
      is_published?: boolean;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      event_id?: string | null;
      link_type?: string;
      url?: string;
      title?: string | null;
      shared_with_roles?: string[];
      shared_with_department_ids?: string[];
      shared_with_member_ids?: string[];
      is_published?: boolean;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    member_departments: {
      Row: {
      id: string;
      member_id: string;
      department_id: string;
      assignment_type: string;
      is_current: boolean;
      started_at: string;
      ended_at: string | null;
      changed_by: string | null;
      notes: string | null;
      };
      Insert: {
      id?: string;
      member_id: string;
      department_id: string;
      assignment_type?: string;
      is_current?: boolean;
      started_at?: string;
      ended_at?: string | null;
      changed_by?: string | null;
      notes?: string | null;
      };
      Update: {
      id?: string;
      member_id?: string;
      department_id?: string;
      assignment_type?: string;
      is_current?: boolean;
      started_at?: string;
      ended_at?: string | null;
      changed_by?: string | null;
      notes?: string | null;
      };
      Relationships: [];
    };
    member_families: {
      Row: {
      id: string;
      member_id: string;
      family_id: string;
      is_current: boolean;
      started_at: string;
      ended_at: string | null;
      changed_by: string | null;
      notes: string | null;
      };
      Insert: {
      id?: string;
      member_id: string;
      family_id: string;
      is_current?: boolean;
      started_at?: string;
      ended_at?: string | null;
      changed_by?: string | null;
      notes?: string | null;
      };
      Update: {
      id?: string;
      member_id?: string;
      family_id?: string;
      is_current?: boolean;
      started_at?: string;
      ended_at?: string | null;
      changed_by?: string | null;
      notes?: string | null;
      };
      Relationships: [];
    };
    member_profiles: {
      Row: {
      member_id: string;
      current_church: string | null;
      church_location: string | null;
      pastor_name: string | null;
      church_membership_info: string | null;
      referral_info: string | null;
      education: Json;
      profession: string | null;
      employer: string | null;
      professional_qualifications: Json;
      skills: string[];
      previously_choir_member: boolean;
      previous_choir_name: string | null;
      previous_choir_duration: string | null;
      previous_choir_responsibilities: string | null;
      previous_choir_leave_reason: string | null;
      musical_experience: string | null;
      vocal_category: string | null;
      instrument: string | null;
      musical_skills: string[];
      music_training: string | null;
      previous_performance_experience: string | null;
      notes: string | null;
      updated_at: string;
      };
      Insert: {
      member_id: string;
      current_church?: string | null;
      church_location?: string | null;
      pastor_name?: string | null;
      church_membership_info?: string | null;
      referral_info?: string | null;
      education?: Json;
      profession?: string | null;
      employer?: string | null;
      professional_qualifications?: Json;
      skills?: string[];
      previously_choir_member?: boolean;
      previous_choir_name?: string | null;
      previous_choir_duration?: string | null;
      previous_choir_responsibilities?: string | null;
      previous_choir_leave_reason?: string | null;
      musical_experience?: string | null;
      vocal_category?: string | null;
      instrument?: string | null;
      musical_skills?: string[];
      music_training?: string | null;
      previous_performance_experience?: string | null;
      notes?: string | null;
      updated_at?: string;
      };
      Update: {
      member_id?: string;
      current_church?: string | null;
      church_location?: string | null;
      pastor_name?: string | null;
      church_membership_info?: string | null;
      referral_info?: string | null;
      education?: Json;
      profession?: string | null;
      employer?: string | null;
      professional_qualifications?: Json;
      skills?: string[];
      previously_choir_member?: boolean;
      previous_choir_name?: string | null;
      previous_choir_duration?: string | null;
      previous_choir_responsibilities?: string | null;
      previous_choir_leave_reason?: string | null;
      musical_experience?: string | null;
      vocal_category?: string | null;
      instrument?: string | null;
      musical_skills?: string[];
      music_training?: string | null;
      previous_performance_experience?: string | null;
      notes?: string | null;
      updated_at?: string;
      };
      Relationships: [];
    };
    members: {
      Row: {
      id: string;
      member_number: string;
      user_id: string | null;
      application_id: string | null;
      first_name: string;
      middle_name: string | null;
      last_name: string;
      preferred_name: string | null;
      gender: string | null;
      date_of_birth: string | null;
      photo_url: string | null;
      nationality: string | null;
      national_id_number: string | null;
      email: string | null;
      phone: string | null;
      whatsapp_number: string | null;
      physical_address: string | null;
      region: string | null;
      district: string | null;
      emergency_contact_name: string | null;
      emergency_contact_phone: string | null;
      primary_department_id: string | null;
      family_id: string | null;
      membership_status: string;
      joined_at: string | null;
      exited_at: string | null;
      exit_reason: string | null;
      qr_token: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      member_number: string;
      user_id?: string | null;
      application_id?: string | null;
      first_name: string;
      middle_name?: string | null;
      last_name: string;
      preferred_name?: string | null;
      gender?: string | null;
      date_of_birth?: string | null;
      photo_url?: string | null;
      nationality?: string | null;
      national_id_number?: string | null;
      email?: string | null;
      phone?: string | null;
      whatsapp_number?: string | null;
      physical_address?: string | null;
      region?: string | null;
      district?: string | null;
      emergency_contact_name?: string | null;
      emergency_contact_phone?: string | null;
      primary_department_id?: string | null;
      family_id?: string | null;
      membership_status?: string;
      joined_at?: string | null;
      exited_at?: string | null;
      exit_reason?: string | null;
      qr_token?: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      member_number?: string;
      user_id?: string | null;
      application_id?: string | null;
      first_name?: string;
      middle_name?: string | null;
      last_name?: string;
      preferred_name?: string | null;
      gender?: string | null;
      date_of_birth?: string | null;
      photo_url?: string | null;
      nationality?: string | null;
      national_id_number?: string | null;
      email?: string | null;
      phone?: string | null;
      whatsapp_number?: string | null;
      physical_address?: string | null;
      region?: string | null;
      district?: string | null;
      emergency_contact_name?: string | null;
      emergency_contact_phone?: string | null;
      primary_department_id?: string | null;
      family_id?: string | null;
      membership_status?: string;
      joined_at?: string | null;
      exited_at?: string | null;
      exit_reason?: string | null;
      qr_token?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    notification_templates: {
      Row: {
      id: string;
      code: string;
      name: string;
      channel_subject: string | null;
      body_template: string;
      default_channels: string[];
      is_active: boolean;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      code: string;
      name: string;
      channel_subject?: string | null;
      body_template: string;
      default_channels?: string[];
      is_active?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      code?: string;
      name?: string;
      channel_subject?: string | null;
      body_template?: string;
      default_channels?: string[];
      is_active?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    notifications: {
      Row: {
      id: string;
      recipient_user_id: string;
      template_id: string | null;
      channel: string;
      subject: string | null;
      body: string;
      triggering_event: string | null;
      triggering_record_type: string | null;
      triggering_record_id: string | null;
      status: string;
      sent_at: string | null;
      read_at: string | null;
      failure_reason: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      recipient_user_id: string;
      template_id?: string | null;
      channel: string;
      subject?: string | null;
      body: string;
      triggering_event?: string | null;
      triggering_record_type?: string | null;
      triggering_record_id?: string | null;
      status?: string;
      sent_at?: string | null;
      read_at?: string | null;
      failure_reason?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      recipient_user_id?: string;
      template_id?: string | null;
      channel?: string;
      subject?: string | null;
      body?: string;
      triggering_event?: string | null;
      triggering_record_type?: string | null;
      triggering_record_id?: string | null;
      status?: string;
      sent_at?: string | null;
      read_at?: string | null;
      failure_reason?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    permissions: {
      Row: {
      id: string;
      code: string;
      module: string;
      resource: string;
      action: string;
      description: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      code: string;
      module: string;
      resource: string;
      action: string;
      description?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      code?: string;
      module?: string;
      resource?: string;
      action?: string;
      description?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    playlist_items: {
      Row: {
      id: string;
      playlist_id: string;
      sequence_number: number;
      song_title: string;
      musical_key: string | null;
      duration_seconds: number | null;
      lead_vocal_member_id: string | null;
      backing_vocal_member_ids: string[];
      instrument: string | null;
      technical_notes: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      playlist_id: string;
      sequence_number: number;
      song_title: string;
      musical_key?: string | null;
      duration_seconds?: number | null;
      lead_vocal_member_id?: string | null;
      backing_vocal_member_ids?: string[];
      instrument?: string | null;
      technical_notes?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      playlist_id?: string;
      sequence_number?: number;
      song_title?: string;
      musical_key?: string | null;
      duration_seconds?: number | null;
      lead_vocal_member_id?: string | null;
      backing_vocal_member_ids?: string[];
      instrument?: string | null;
      technical_notes?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    playlists: {
      Row: {
      id: string;
      event_id: string;
      title: string;
      shared_with_roles: string[];
      created_by: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      event_id: string;
      title?: string;
      shared_with_roles?: string[];
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      event_id?: string;
      title?: string;
      shared_with_roles?: string[];
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    probation: {
      Row: {
      id: string;
      member_id: string;
      application_id: string | null;
      started_at: string;
      duration_days: number;
      deadline: string;
      assigned_department_id: string | null;
      assigned_family_id: string | null;
      responsible_leader_id: string | null;
      status: string;
      outcome_notes: string | null;
      decided_by: string | null;
      decided_at: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      member_id: string;
      application_id?: string | null;
      started_at?: string;
      duration_days: number;
      deadline: string;
      assigned_department_id?: string | null;
      assigned_family_id?: string | null;
      responsible_leader_id?: string | null;
      status?: string;
      outcome_notes?: string | null;
      decided_by?: string | null;
      decided_at?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      member_id?: string;
      application_id?: string | null;
      started_at?: string;
      duration_days?: number;
      deadline?: string;
      assigned_department_id?: string | null;
      assigned_family_id?: string | null;
      responsible_leader_id?: string | null;
      status?: string;
      outcome_notes?: string | null;
      decided_by?: string | null;
      decided_at?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    procurement_requests: {
      Row: {
      id: string;
      expense_request_id: string;
      vendor_id: string | null;
      description: string;
      status: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      expense_request_id: string;
      vendor_id?: string | null;
      description: string;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      expense_request_id?: string;
      vendor_id?: string | null;
      description?: string;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    purchase_orders: {
      Row: {
      id: string;
      procurement_request_id: string;
      vendor_id: string;
      amount: number;
      currency: string;
      purchased_at: string | null;
      paid_at: string | null;
      payment_status: string;
      created_asset_id: string | null;
      created_at: string;
      };
      Insert: {
      id?: string;
      procurement_request_id: string;
      vendor_id: string;
      amount: number;
      currency?: string;
      purchased_at?: string | null;
      paid_at?: string | null;
      payment_status?: string;
      created_asset_id?: string | null;
      created_at?: string;
      };
      Update: {
      id?: string;
      procurement_request_id?: string;
      vendor_id?: string;
      amount?: number;
      currency?: string;
      purchased_at?: string | null;
      paid_at?: string | null;
      payment_status?: string;
      created_asset_id?: string | null;
      created_at?: string;
      };
      Relationships: [];
    };
    role_permissions: {
      Row: {
      role_id: string;
      permission_id: string;
      created_at: string;
      };
      Insert: {
      role_id: string;
      permission_id: string;
      created_at?: string;
      };
      Update: {
      role_id?: string;
      permission_id?: string;
      created_at?: string;
      };
      Relationships: [];
    };
    roles: {
      Row: {
      id: string;
      code: string;
      name: string;
      description: string | null;
      is_system_role: boolean;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      code: string;
      name: string;
      description?: string | null;
      is_system_role?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      code?: string;
      name?: string;
      description?: string | null;
      is_system_role?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    system_settings: {
      Row: {
      id: string;
      setting_key: string;
      value: Json;
      value_type: string;
      description: string | null;
      updated_by: string | null;
      updated_at: string;
      created_at: string;
      };
      Insert: {
      id?: string;
      setting_key: string;
      value: Json;
      value_type?: string;
      description?: string | null;
      updated_by?: string | null;
      updated_at?: string;
      created_at?: string;
      };
      Update: {
      id?: string;
      setting_key?: string;
      value?: Json;
      value_type?: string;
      description?: string | null;
      updated_by?: string | null;
      updated_at?: string;
      created_at?: string;
      };
      Relationships: [];
    };
    technical_riders: {
      Row: {
      id: string;
      event_id: string;
      pa_requirements: string | null;
      lighting_requirements: string | null;
      led_display_requirements: string | null;
      camera_requirements: string | null;
      recording_requirements: string | null;
      power_requirements: string | null;
      stage_requirements: string | null;
      monitoring_requirements: string | null;
      crew_notes: string | null;
      setup_time: string | null;
      soundcheck_time: string | null;
      technical_notes: string | null;
      prepared_by: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      event_id: string;
      pa_requirements?: string | null;
      lighting_requirements?: string | null;
      led_display_requirements?: string | null;
      camera_requirements?: string | null;
      recording_requirements?: string | null;
      power_requirements?: string | null;
      stage_requirements?: string | null;
      monitoring_requirements?: string | null;
      crew_notes?: string | null;
      setup_time?: string | null;
      soundcheck_time?: string | null;
      technical_notes?: string | null;
      prepared_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      event_id?: string;
      pa_requirements?: string | null;
      lighting_requirements?: string | null;
      led_display_requirements?: string | null;
      camera_requirements?: string | null;
      recording_requirements?: string | null;
      power_requirements?: string | null;
      stage_requirements?: string | null;
      monitoring_requirements?: string | null;
      crew_notes?: string | null;
      setup_time?: string | null;
      soundcheck_time?: string | null;
      technical_notes?: string | null;
      prepared_by?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    trips: {
      Row: {
      id: string;
      event_id: string;
      destination: string | null;
      vehicle_requirement: string | null;
      driver_name: string | null;
      transport_vendor_id: string | null;
      accommodation_vendor_id: string | null;
      departure_at: string | null;
      arrival_at: string | null;
      return_departure_at: string | null;
      return_arrival_at: string | null;
      estimated_cost: number | null;
      actual_cost: number | null;
      currency: string;
      notes: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      event_id: string;
      destination?: string | null;
      vehicle_requirement?: string | null;
      driver_name?: string | null;
      transport_vendor_id?: string | null;
      accommodation_vendor_id?: string | null;
      departure_at?: string | null;
      arrival_at?: string | null;
      return_departure_at?: string | null;
      return_arrival_at?: string | null;
      estimated_cost?: number | null;
      actual_cost?: number | null;
      currency?: string;
      notes?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      event_id?: string;
      destination?: string | null;
      vehicle_requirement?: string | null;
      driver_name?: string | null;
      transport_vendor_id?: string | null;
      accommodation_vendor_id?: string | null;
      departure_at?: string | null;
      arrival_at?: string | null;
      return_departure_at?: string | null;
      return_arrival_at?: string | null;
      estimated_cost?: number | null;
      actual_cost?: number | null;
      currency?: string;
      notes?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    uniform_assignments: {
      Row: {
      id: string;
      uniform_id: string;
      member_id: string;
      event_id: string | null;
      quantity: number;
      assigned_at: string;
      assigned_by: string | null;
      returned_at: string | null;
      return_condition: string | null;
      status: string;
      created_at: string;
      };
      Insert: {
      id?: string;
      uniform_id: string;
      member_id: string;
      event_id?: string | null;
      quantity?: number;
      assigned_at?: string;
      assigned_by?: string | null;
      returned_at?: string | null;
      return_condition?: string | null;
      status?: string;
      created_at?: string;
      };
      Update: {
      id?: string;
      uniform_id?: string;
      member_id?: string;
      event_id?: string | null;
      quantity?: number;
      assigned_at?: string;
      assigned_by?: string | null;
      returned_at?: string | null;
      return_condition?: string | null;
      status?: string;
      created_at?: string;
      };
      Relationships: [];
    };
    uniforms: {
      Row: {
      id: string;
      uniform_type: string;
      size: string | null;
      quantity_total: number;
      quantity_available: number;
      condition: string;
      storage_location: string | null;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      uniform_type: string;
      size?: string | null;
      quantity_total?: number;
      quantity_available?: number;
      condition?: string;
      storage_location?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      uniform_type?: string;
      size?: string | null;
      quantity_total?: number;
      quantity_available?: number;
      condition?: string;
      storage_location?: string | null;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    user_roles: {
      Row: {
      id: string;
      user_id: string;
      role_id: string;
      scope_type: string | null;
      scope_id: string | null;
      granted_by: string | null;
      granted_at: string;
      revoked_at: string | null;
      };
      Insert: {
      id?: string;
      user_id: string;
      role_id: string;
      scope_type?: string | null;
      scope_id?: string | null;
      granted_by?: string | null;
      granted_at?: string;
      revoked_at?: string | null;
      };
      Update: {
      id?: string;
      user_id?: string;
      role_id?: string;
      scope_type?: string | null;
      scope_id?: string | null;
      granted_by?: string | null;
      granted_at?: string;
      revoked_at?: string | null;
      };
      Relationships: [];
    };
    users: {
      Row: {
      id: string;
      email: string | null;
      username: string | null;
      phone: string | null;
      display_name: string;
      is_active: boolean;
      last_login_at: string | null;
      mfa_enabled: boolean;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id: string;
      email?: string | null;
      username?: string | null;
      phone?: string | null;
      display_name: string;
      is_active?: boolean;
      last_login_at?: string | null;
      mfa_enabled?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      email?: string | null;
      username?: string | null;
      phone?: string | null;
      display_name?: string;
      is_active?: boolean;
      last_login_at?: string | null;
      mfa_enabled?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    vendor_categories: {
      Row: {
      id: string;
      name: string;
      created_at: string;
      };
      Insert: {
      id?: string;
      name: string;
      created_at?: string;
      };
      Update: {
      id?: string;
      name?: string;
      created_at?: string;
      };
      Relationships: [];
    };
    vendors: {
      Row: {
      id: string;
      name: string;
      category_id: string;
      contact_person: string | null;
      phone: string | null;
      email: string | null;
      address: string | null;
      tax_information: string | null;
      bank_payment_information: string | null;
      performance_notes: string | null;
      status: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      name: string;
      category_id: string;
      contact_person?: string | null;
      phone?: string | null;
      email?: string | null;
      address?: string | null;
      tax_information?: string | null;
      bank_payment_information?: string | null;
      performance_notes?: string | null;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      name?: string;
      category_id?: string;
      contact_person?: string | null;
      phone?: string | null;
      email?: string | null;
      address?: string | null;
      tax_information?: string | null;
      bank_payment_information?: string | null;
      performance_notes?: string | null;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    votes: {
      Row: {
      id: string;
      agenda_id: string;
      voter_id: string;
      choice: string;
      cast_at: string;
      };
      Insert: {
      id?: string;
      agenda_id: string;
      voter_id: string;
      choice: string;
      cast_at?: string;
      };
      Update: {
      id?: string;
      agenda_id?: string;
      voter_id?: string;
      choice?: string;
      cast_at?: string;
      };
      Relationships: [];
    };
    workflow_definition_steps: {
      Row: {
      id: string;
      workflow_definition_id: string;
      step_order: number;
      required_role_code: string | null;
      required_user_id: string | null;
      is_mandatory: boolean;
      };
      Insert: {
      id?: string;
      workflow_definition_id: string;
      step_order: number;
      required_role_code?: string | null;
      required_user_id?: string | null;
      is_mandatory?: boolean;
      };
      Update: {
      id?: string;
      workflow_definition_id?: string;
      step_order?: number;
      required_role_code?: string | null;
      required_user_id?: string | null;
      is_mandatory?: boolean;
      };
      Relationships: [];
    };
    workflow_definitions: {
      Row: {
      id: string;
      record_type: string;
      name: string;
      is_active: boolean;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      record_type: string;
      name: string;
      is_active?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      record_type?: string;
      name?: string;
      is_active?: boolean;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    workflow_instances: {
      Row: {
      id: string;
      workflow_definition_id: string;
      record_type: string;
      record_id: string;
      current_step_order: number;
      status: string;
      created_at: string;
      updated_at: string;
      };
      Insert: {
      id?: string;
      workflow_definition_id: string;
      record_type: string;
      record_id: string;
      current_step_order?: number;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Update: {
      id?: string;
      workflow_definition_id?: string;
      record_type?: string;
      record_id?: string;
      current_step_order?: number;
      status?: string;
      created_at?: string;
      updated_at?: string;
      };
      Relationships: [];
    };
    workflow_step_decisions: {
      Row: {
      id: string;
      workflow_instance_id: string;
      step_order: number;
      approver_id: string;
      approver_role_code: string | null;
      decision: string;
      comment: string | null;
      decided_at: string;
      ip_address: string | null;
      device_info: string | null;
      };
      Insert: {
      id?: string;
      workflow_instance_id: string;
      step_order: number;
      approver_id: string;
      approver_role_code?: string | null;
      decision: string;
      comment?: string | null;
      decided_at?: string;
      ip_address?: string | null;
      device_info?: string | null;
      };
      Update: {
      id?: string;
      workflow_instance_id?: string;
      step_order?: number;
      approver_id?: string;
      approver_role_code?: string | null;
      decision?: string;
      comment?: string | null;
      decided_at?: string;
      ip_address?: string | null;
      device_info?: string | null;
      };
      Relationships: [];
    };
    };
    Views: {
    agenda_results: {
      Row: {
      agenda_id: string | null;
      yes_count: number | null;
      no_count: number | null;
      abstain_count: number | null;
      total_votes: number | null;
      };
      Relationships: [];
    };
    contribution_campaign_summary: {
      Row: {
      campaign_id: string | null;
      name: string | null;
      target_amount: number | null;
      total_contributors: number | null;
      total_contributed: number | null;
      outstanding_amount: number | null;
      achievement_percentage: number | null;
      };
      Relationships: [];
    };
    member_attendance_summary: {
      Row: {
      member_id: string | null;
      sessions_present: number | null;
      sessions_recorded: number | null;
      attendance_percentage: number | null;
      };
      Relationships: [];
    };
    };
    // NOT introspected from pg_proc — hand-maintained below. Phase 8.3 found
    // this list had silently fallen out of sync with reality: three RPCs
    // added by earlier phases (find_member_by_number_for_discipline,
    // apply_disciplinary_membership_status, record_workflow_decision) were
    // hand-added directly to the checked-in database.types.ts and never
    // added HERE, so the previous re-run of this script (this phase, before
    // the fix) silently deleted their type signatures. Whenever a migration
    // adds or changes a SECURITY DEFINER RPC the app calls via
    // `client.rpc(...)`, add/update its entry here too, in the SAME
    // migration/phase — not just in the checked-in .ts output — or the next
    // `pnpm gen:types` run will quietly drop it again.
    Functions: {
      has_permission: {
        Args: { p_permission_code: string };
        Returns: boolean;
      };
      has_role: {
        Args: { p_role_code: string };
        Returns: boolean;
      };
      next_formatted_id: {
        Args: { p_sequence_key: string; p_format: string };
        Returns: string;
      };
      find_member_by_number_for_discipline: {
        Args: { p_member_number: string };
        Returns: { id: string; first_name: string; last_name: string; member_number: string; membership_status: string }[];
      };
      apply_disciplinary_membership_status: {
        Args: { p_member_id: string; p_status: string; p_exit_reason?: string | null };
        Returns: undefined;
      };
      record_workflow_decision: {
        Args: { p_workflow_instance_id: string; p_decision: string; p_comment?: string | null };
        Returns: { id: string; status: string; current_step_order: number; record_type: string; record_id: string }[];
      };
      start_gate_pass_workflow: {
        Args: { p_gate_pass_id: string };
        Returns: { id: string; workflow_definition_id: string; record_type: string; record_id: string; current_step_order: number; status: string; created_at: string; updated_at: string }[];
      };
      start_expense_request_workflow: {
        Args: { p_expense_request_id: string };
        Returns: { id: string; workflow_definition_id: string; record_type: string; record_id: string; current_step_order: number; status: string; created_at: string; updated_at: string }[];
      };
      send_notification: {
        Args: {
          p_audience: string;
          p_department_id: string | null;
          p_family_id: string | null;
          p_user_ids: string[] | null;
          p_channel: string;
          p_subject: string | null;
          p_body: string;
          p_template_id: string | null;
          p_triggering_event: string | null;
          p_triggering_record_type: string | null;
          p_triggering_record_id: string | null;
        };
        Returns: {
          id: string;
          recipient_user_id: string;
          template_id: string | null;
          channel: string;
          subject: string | null;
          body: string;
          triggering_event: string | null;
          triggering_record_type: string | null;
          triggering_record_id: string | null;
          status: string;
          sent_at: string | null;
          read_at: string | null;
          failure_reason: string | null;
          created_at: string;
        }[];
      };
    };
  };
}
