/// <reference types="expo/types" />

// NOTE: this file is normally auto-generated by the Expo CLI on `expo
// start`/`expo export`. It is hand-written and checked in here instead so
// `tsc --noEmit` (this app's `typecheck`/`lint` script, run in CI/this
// environment without ever invoking the Expo CLI dev server) does not
// depend on a generated file that may not exist yet.
