#!/usr/bin/env node
/**
 * Generates src/database.types.ts by introspecting information_schema on a
 * REAL running Postgres instance (DATABASE_URL) — no Docker, no hosted
 * Supabase project required. This is a stand-in for `supabase gen types
 * typescript --project-id <ref>`, which is the command to run instead once
 * this project is linked to a real hosted Supabase project (its introspection
 * container image lives on a registry this sandbox's network policy blocks —
 * see docs/AUTHENTICATION.md "Environment constraints"). Re-run this script
 * after every migration change in the meantime; the output is equivalent in
 * shape to Supabase's own generated Database type (Tables.<name>.Row/Insert/Update),
 * so swapping to the real generator later is a drop-in replacement.
 */
import pg from "pg";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const DATABASE_URL = process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/ngc_erp";
const OUT_FILE = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "database.types.ts");

const PG_TO_TS = {
  uuid: "string",
  text: "string",
  citext: "string",
  varchar: "string",
  "character varying": "string",
  date: "string",
  time: "string",
  "time without time zone": "string",
  timestamp: "string",
  "timestamp without time zone": "string",
  timestamptz: "string",
  "timestamp with time zone": "string",
  boolean: "boolean",
  integer: "number",
  bigint: "number",
  smallint: "number",
  numeric: "number",
  real: "number",
  "double precision": "number",
  jsonb: "Json",
  json: "Json",
  inet: "string",
  "USER-DEFINED": "string",
  ARRAY: "unknown[]",
};

function tsType(dataType, udtName) {
  if (dataType === "ARRAY") {
    const base = udtName?.startsWith("_") ? udtName.slice(1) : udtName;
    const inner = PG_TO_TS[base] ?? "unknown";
    return `${inner}[]`;
  }
  return PG_TO_TS[dataType] ?? PG_TO_TS[udtName] ?? "unknown";
}

async function main() {
  const client = new pg.Client({ connectionString: DATABASE_URL });
  await client.connect();

  const { rows: columns } = await client.query(`
    select table_name, column_name, data_type, udt_name, is_nullable, column_default
    from information_schema.columns
    where table_schema = 'public'
    order by table_name, ordinal_position
  `);

  const { rows: tableTypeRows } = await client.query(`
    select table_name, table_type
    from information_schema.tables
    where table_schema = 'public'
  `);
  const tableTypeByName = Object.fromEntries(tableTypeRows.map((r) => [r.table_name, r.table_type]));

  await client.end();

  const byTable = new Map();
  for (const col of columns) {
    if (!byTable.has(col.table_name)) byTable.set(col.table_name, []);
    byTable.get(col.table_name).push(col);
  }

  const tableBlocks = [];
  const viewBlocks = [];

  for (const [tableName, cols] of [...byTable.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    const isView = tableTypeByName[tableName] === "VIEW";
    const rowFields = cols
      .map((c) => {
        const t = tsType(c.data_type, c.udt_name);
        const nullable = c.is_nullable === "YES";
        return `      ${c.column_name}: ${t}${nullable ? " | null" : ""};`;
      })
      .join("\n");

    if (isView) {
      viewBlocks.push(
        `    ${tableName}: {\n      Row: {\n${rowFields}\n      };\n      Relationships: [];\n    };`
      );
      continue;
    }

    const insertFields = cols
      .map((c) => {
        const t = tsType(c.data_type, c.udt_name);
        const nullable = c.is_nullable === "YES";
        const hasDefault = c.column_default !== null;
        const optional = nullable || hasDefault;
        return `      ${c.column_name}${optional ? "?" : ""}: ${t}${nullable ? " | null" : ""};`;
      })
      .join("\n");

    const updateFields = cols
      .map((c) => {
        const t = tsType(c.data_type, c.udt_name);
        const nullable = c.is_nullable === "YES";
        return `      ${c.column_name}?: ${t}${nullable ? " | null" : ""};`;
      })
      .join("\n");

    tableBlocks.push(
      `    ${tableName}: {\n      Row: {\n${rowFields}\n      };\n      Insert: {\n${insertFields}\n      };\n      Update: {\n${updateFields}\n      };\n      Relationships: [];\n    };`
    );
  }

  const output = `// AUTO-GENERATED by packages/db/scripts/generate-types.mjs — do not hand-edit.
// Regenerate after any migration change: \`pnpm --filter @ngc/db gen:types\`
// (requires DATABASE_URL to point at a Postgres instance with all migrations applied).
//
// Once this project is linked to a real hosted Supabase project, prefer
// \`supabase gen types typescript --project-id <ref> > src/database.types.ts\`
// instead — the shape below matches its output, so nothing else needs to change.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
${tableBlocks.join("\n")}
    };
    Views: {
${viewBlocks.join("\n")}
    };
    // NOT introspected from pg_proc — hand-maintained below. Phase 8.3 found
    // this list had silently fallen out of sync with reality: three RPCs
    // added by earlier phases (find_member_by_number_for_discipline,
    // apply_disciplinary_membership_status, record_workflow_decision) were
    // hand-added directly to the checked-in database.types.ts and never
    // added HERE, so the previous re-run of this script (this phase, before
    // the fix) silently deleted their type signatures. Whenever a migration
    // adds or changes a SECURITY DEFINER RPC the app calls via
    // \`client.rpc(...)\`, add/update its entry here too, in the SAME
    // migration/phase — not just in the checked-in .ts output — or the next
    // \`pnpm gen:types\` run will quietly drop it again.
    Functions: {
      has_permission: {
        Args: { p_permission_code: string };
        Returns: boolean;
      };
      has_role: {
        Args: { p_role_code: string };
        Returns: boolean;
      };
      next_formatted_id: {
        Args: { p_sequence_key: string; p_format: string };
        Returns: string;
      };
      find_member_by_number_for_discipline: {
        Args: { p_member_number: string };
        Returns: { id: string; first_name: string; last_name: string; member_number: string; membership_status: string }[];
      };
      apply_disciplinary_membership_status: {
        Args: { p_member_id: string; p_status: string; p_exit_reason?: string | null };
        Returns: undefined;
      };
      record_workflow_decision: {
        Args: { p_workflow_instance_id: string; p_decision: string; p_comment?: string | null };
        Returns: { id: string; status: string; current_step_order: number; record_type: string; record_id: string }[];
      };
      start_gate_pass_workflow: {
        Args: { p_gate_pass_id: string };
        Returns: { id: string; workflow_definition_id: string; record_type: string; record_id: string; current_step_order: number; status: string; created_at: string; updated_at: string }[];
      };
      start_expense_request_workflow: {
        Args: { p_expense_request_id: string };
        Returns: { id: string; workflow_definition_id: string; record_type: string; record_id: string; current_step_order: number; status: string; created_at: string; updated_at: string }[];
      };
      send_notification: {
        Args: {
          p_audience: string;
          p_department_id: string | null;
          p_family_id: string | null;
          p_user_ids: string[] | null;
          p_channel: string;
          p_subject: string | null;
          p_body: string;
          p_template_id: string | null;
          p_triggering_event: string | null;
          p_triggering_record_type: string | null;
          p_triggering_record_id: string | null;
        };
        Returns: {
          id: string;
          recipient_user_id: string;
          template_id: string | null;
          channel: string;
          subject: string | null;
          body: string;
          triggering_event: string | null;
          triggering_record_type: string | null;
          triggering_record_id: string | null;
          status: string;
          sent_at: string | null;
          read_at: string | null;
          failure_reason: string | null;
          created_at: string;
        }[];
      };
    };
  };
}
`;

  writeFileSync(OUT_FILE, output);
  console.log(`Wrote ${OUT_FILE} (${byTable.size} tables/views).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
